### ISSUE TITLE
help

### ISSUE THREAD

**Issue by noxv3** [FlawwsX/mythic_notify#3]
I made a mistake when you write the notification in the client.lua

> [picture](https://prnt.sc/11rn5du)

**Comment by MAC-gg** [comment]
I am getting the same error. All code seems to be correct. Did something change with Fivem?

**Comment by MAC-gg** [comment]
I was able to get it to work with the following line of code instead of what is in the docs:

`exports.mythic_notify:SendAlert('inform', 'test')`
